import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { logo } from "./services/assets.service";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hassam Ullah",
  description: "Generated by create next app",
  icons:[
    logo.src
  ]
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
