enum TechnologiesEnum {
    ts = "TypeScript",
    node = "Node.js",
    express = "Express",
    react = "React",
    mongo = "MongoDB",
    typeOrm = "TypeORM",
    mongoose = "Mongoose",
    psql = "PostgreSQL",
    prisma = "Prisma",
    aws_ec2 = "AWS EC2",
    aws_s3 = "AWS S3",
    digitalOcean = "Digital Ocean",
    sendgrid = "SendGrid",
    chatGpt = "ChatGPT",
    socket = "Socket.io",
    googleCloud = "Google Cloud Platform",
    firebase = "Firebase",
    vite = "Vite",
    next = "Next.js",
    pm2 = "PM2",
    nginx = "Nginx",
    azure = "Microsoft Azure",
    github = "GitHub",
    mysql = "MySQL",
    puppeteer = "Puppeteer",
    angular = "Angular",
    stripe = "Stripe",
    paypal = "PayPal",
    tensorflow = "Tensorflow",
    redux = "Redux Toolkit",
    web3 = "Web3.js",
    ethers= "Ethers.js"
}

export { TechnologiesEnum }