enum TechnologiesEnum {
  ts = "TypeScript",
  node = "Node.js",
  nest = "Nest.js",
  express = "Express",
  react = "React",
  mongo = "MongoDB",
  docker = "Docker",
  typeOrm = "TypeORM",
  mongoose = "Mongoose",
  psql = "PostgreSQL",
  prisma = "Prisma",
  aws = "AWS",
  aws_ec2 = "AWS EC2",
  aws_s3 = "AWS S3",
  digitalOcean = "Digital Ocean",
  sendgrid = "SendGrid",
  chatGpt = "ChatGPT",
  socket = "Socket.io",
  googleCloud = "Google Cloud Platform",
  firebase = "Firebase",
  vite = "Vite",
  next = "Next.js",
  pm2 = "PM2",
  nginx = "Nginx",
  azure = "Microsoft Azure",
  github = "GitHub",
  mysql = "MySQL",
  puppeteer = "Puppeteer",
  agora = "Agora SDK",
  telegram = "TelegramBot API",
  angular = "Angular",
  stripe = "Stripe",
  paypal = "PayPal",
  tensorflow = "Tensorflow",
  redux = "Redux Toolkit",
  web3 = "Web3.js",
  ethers = "Ethers.js",
  material = "Material UI",
  flowbite = "FlowBite",
  tailwind = "Tailwind",
  nextui = "Next UI",
  bootstrap = "Bootstrap",
  ethereum = "Ethereum",
  swiper = "Swiper.js",
  reactIcons = "React Icons",
  particles = "Particles.js",
  chrono = "React-Chrono",
  scroll = "React-Scroll",
  forms = "React-Hook-Form",
}

enum ThemesEnum {
  ocean = "ocean",
  forest = "forest",
  sunset = "sunset",
  ghost = "ghost",
}

enum ColorsEnum {
  ocean = "blue",
  forest = "darkgreen",
  sunset = "orange",
  ghost = "white",
}

export { TechnologiesEnum, ThemesEnum, ColorsEnum };
